# Configure Rubocop to use the config file in the Scaffolint GitHub repo
AllCops:
  Exclude:
    - 'testing/*'
inherit_from:
  - https://raw.githubusercontent.com/makersacademy/scaffolint/v1.1.0/.rubocop.yml